### ISSUE TITLE
Import user configuration from older Lutris installs

### ISSUE THREAD

**Issue by lengau** [CapeCrusader321/Lutris-snap#10]
It would be nice to import the user's configuration from non-snapped Lutris installs.

This would probably require the super-privileged [personal-files interface](https://snapcraft.io/docs/personal-files-interface), but I believe it would just need to read from $HOME/.local/share/lutris and $HOME/.config/lutris

**Comment by CapeCrusader321** [comment]
I will need more insight on what you are suggesting plus a pr is much more appreciated

**Comment by lengau** [comment]
I've made #17 for this. Please note that this requires the [personal-files interface](https://snapcraft.io/docs/personal-files-interface), which is [super privileged](https://snapcraft.io/docs/super-privileged-interfaces), so that PR should not be merged until the snap has [received the appropriate permissions](https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks), as it will prevent the snap from being published in the store.

**Comment by CapeCrusader321** [comment]
@lengau  Do individual projects like this get this privileged interface, if yes i will open a request
